### ISSUE TITLE
Revealed timeStamps are on table view if I pulled to review and scroll at the same time

### ISSUE THREAD

**Issue by yarodevuci** [shaps80/iMessageStyleReveal#17] opened 2017-02-26 04:18 UTC
@shaps80 
hello
If I pull to reveal time stamps and scroll table view in the same time and let it go then timestamps are remaining on table view .. 
Any ideas how to fix that? 
I use SWIFT 3 branch

**Comment by shaps80** [comment] 2017-02-26 08:57
Can you show me a screenshot of what you mean? I'm not sure I understand.

**Comment by yarodevuci** [comment] 2017-02-26 09:05
![simulator screen shot feb 26 2017 1 04 15 am](https://cloud.githubusercontent.com/assets/13408859/23338438/8137a2f6-fbbf-11e6-9cf4-fb1158aeea77.png)

@shaps80 Here is the example. Once again if I pull to reveal and then scroll the table view you can see that some timestamps are remaining on table view. To dismiss them I have to reveal the timestamps again
Using Swift 3, iOS10.2

**Comment by shaps80** [comment] 2017-02-26 14:14
Hmmm.. yeah I was going to say, my example does this perfectly. 

Is there a difference in terms of how the views are created? XIB? Programmatic?

**Comment by yarodevuci** [comment] 2017-02-26 14:19
@shaps80 I am using two xib for Left Side message and Right Side Message

**Comment by shaps80** [comment] 2017-02-26 14:27
Oh wait you're using both left and right?

**Comment by shaps80** [comment] 2017-02-26 14:28
Not sure if I tested/supported using both. On the same row?

**Comment by shaps80** [comment] 2017-02-26 14:30
Can you make are you're using 2.0 the new release. It has a slight API change for reuse. Otherwise it's the same and may fix your issue.

**Comment by yarodevuci** [comment] 2017-02-26 14:54
@shaps80 To be more specific if message is outgoing I use xib 1 if message is incoming using xib 2.
I am using SLKTextVIewController.

**Comment by shaps80** [comment] 2017-02-26 15:11
Hmm then I'm not sure. Is it possible you could create a little sample app that produces the same result? Without seeing the code I'm not sure since my example does something similar without issue. Plus I have this same implemetantion in a lot of other apps that haven't reported this result.

**Comment by shaps80** [comment] 2017-02-26 15:14
I could be a lot more helpful with code. Sorry you're having issues. 

Only thing you could try -- since it changed in 2.0 -- look at this line:

    internal weak var revealView: RevealableView?

And remove the weak modifier. 

Not sure if it'll have any impact.

**Comment by shaps80** [comment] 2017-02-26 16:20
I might have some time tonight to try my demo app with SLKTextViewController. Maybe there's a clash here.

**Comment by yarodevuci** [comment] 2017-02-27 00:33
@shaps80 Thank you so much for the support. I will try to remove 

`weak`reference and will let you know. In the mean time I will try to prep an example for you

 ref

**Comment by yarodevuci** [comment] 2017-02-27 09:11
@shaps80 What is this line in you example code for ?
`tableView.registerNib(UINib(nibName: "TimestampView", bundle: nil), forRevealableViewReuseIdentifier: "name")`

**Comment by yarodevuci** [comment] 2017-02-27 09:23
![simulator screen shot feb 27 2017 1 22 11 am](https://cloud.githubusercontent.com/assets/13408859/23355568/2ee42034-fc8b-11e6-961b-4d517ab62784.png)

I was able to reproduce this bug in your example by playing around with it for few minutes. Pulling and scrolling in the same time, If you look at screen, one time stamp got stuck on the view...

**Comment by shaps80** [comment] 2017-02-27 09:34
Oh interesting. That line is to register the nib so that we can dequeue it later. Its overly simplified in the Example to get called within `cellForRow:` but in production code you would generally add it in `viewDidLoad` only so that it doesn't get re-called constantly. Not sure how expensive it is or if its even allowed.

Try moving it to `viewDidLoad` in your own project and let me know the result.

Thanks and good luck.

**Comment by yarodevuci** [comment] 2017-02-27 09:41
@shaps80 In you example you have two lines

```
tableView.registerNib(UINib(nibName: "TimestampView", bundle: nil), forRevealableViewReuseIdentifier: "timestamp")
        tableView.registerNib(UINib(nibName: "TimestampView", bundle: nil), forRevealableViewReuseIdentifier: "name")
```

So I assume line below is not needed? By the way it is in viewDidLoad

**Comment by yarodevuci** [comment] 2017-02-27 09:43
Check out gif too @shaps80

**Comment by yarodevuci** [comment] 2017-02-27 09:55
Here is the gif just in case;)
![1kf0k1](https://cloud.githubusercontent.com/assets/13408859/23356716/c6313496-fc8f-11e6-83f1-2e8d0815ad36.gif)

**Comment by shaps80** [comment] 2017-02-27 09:57
Oh interesting. Yeah maybe I forgot to remove an old line. But assuming you don't have the same issue. 

Could you submit a PR of my demo as you've changed it.  Then I'll pull and check it out. Thanks.

**Comment by yarodevuci** [comment] 2017-02-27 12:40
@shaps80 I have not changed anything except copy paste your messages array 3 times
and I commented these lines in heightForRow. Not sure if I have to use it at all or not. 

       ```
 let message = messages[indexPath.item]
        
        if let cell = tableView.dequeueReusableCell(withIdentifier: message.cell.rawValue) as? TableViewCell {
            configure(cell: cell, at: indexPath, with: message)
            return cell.contentView.systemLayoutSizeFitting(UILayoutFittingExpandedSize).height
        }
```

**Comment by shaps80** [comment] 2017-02-27 13:18
Those lines allow auto-sizing cells. You probably have your own code for that so its fine. Ok let me try it out.

**Comment by shaps80** [comment] 2017-02-28 11:49
Interesting -- I am unable to reproduce this in the Example app by doing what you suggest.

Also, I have asked other users if they are experiencing the same issue, so far it seems everyone else is ok.

I'm really not sure how I can be of much more help without having a reproducible issue. I will close this ticket for now, but if you manage to work out how I can see this issue, please feel free to re-open or create a new ticket to discuss.

Sorry I can't be of more help.

**Closed by shaps80** 2017-02-28 11:49 UTC

**Comment by fawzirifai** [comment] 2019-04-29 18:18
Guys did you find a fix for this?

**Comment by shaps80** [comment] 2019-04-29 19:17
It was generally not reproducible AFAIK. I mo longer support this repo since I tend not to use table views anymore. However If you are still interested in submitting aPR I will review 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fawzirifai** [comment] 2019-04-29 19:29
@shaps80 do you mean a simple project to see the bug and trying to fix it? I don’t know how to fix it. Your project is very helpful and I need it for my graduate project, so please if you can help to fix this issue it will be appreciated.

**Comment by shaps80** [comment] 2019-04-29 21:53
Sorry I just don’t have the time these days. Quite busy on other projects and family. Sorry 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fawzirifai** [comment] 2019-04-30 01:22
No problem, but please can you tell me briefly what method you used to hide and show the time stamp? I want to try coding it myself.

**Comment by shaps80** [comment] 2019-04-30 11:01
You will have to checkout the example code or the comments here. I didn’t have this issue so don’t know I’m afraid. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
